// ─────────────────────────────────────────────────────────────────────────────
// 2024 European Parliament election — results by member state and European group.
// AUTO-GENERATED by eu_src/gen-ts.cjs — do not edit by hand.
//
// Sources & method:
//   • Seats per group per country + vote% per national party + party→group affiliation:
//     European Parliament official results datasheets (results.elections.europa.eu).
//     Per-country group seats verified to reproduce the official 720-seat constitutive
//     session exactly (EPP 188 · S&D 136 · PfE 84 · ECR 78 · Renew 77 · Greens/EFA 53 ·
//     The Left 46 · ESN 25 · NI 33).
//   • Raw votes = official valid votes per country × each group's vote share, where a
//     national party's votes are attributed to the European group(s) its elected MEPs
//     joined (split in proportion to seats). Parties that won no seats → "Others" (OTH).
//   • Valid votes per country = electorate × official turnout − official invalid ballots
//     (electorate & invalid: Wikipedia "2024 EP election in <country>"; turnout: EP).
// ─────────────────────────────────────────────────────────────────────────────

export type EuGroupId = 'LEFT' | 'GREENS' | 'SD' | 'RE' | 'EPP' | 'ECR' | 'PfE' | 'ESN' | 'NI' | 'OTH';

export type EuCountryId =
  | 'DE' | 'FR' | 'IT' | 'ES' | 'PL' | 'RO' | 'NL' | 'BE' | 'CZ'
  | 'EL' | 'HU' | 'PT' | 'SE' | 'AT' | 'BG' | 'DK' | 'FI' | 'SK'
  | 'IE' | 'HR' | 'LT' | 'LV' | 'SI' | 'EE' | 'CY' | 'LU' | 'MT';

export interface EuCountry {
  id:         EuCountryId;
  name:       string;
  seats:      number;   // MEPs elected (degressive proportionality)
  electorate: number;   // registered voters (official)
  turnout:    number;   // official turnout %
  validVotes: number;   // electorate*turnout − invalid ballots
  // 2024 raw votes attributed to each European group (+ OTH = no-seat parties)
  raw2024:    Partial<Record<EuGroupId, number>>;
  // official seats won per group in this country (constitutive session)
  seats2024:  Partial<Record<EuGroupId, number>>;
}

// ── EU-wide 2024 totals (constitutive session) ────────────────────────────────
export const EU_TOTAL_SEATS = 720;
export const EU_MAJORITY     = 361;
export const EU_GRAND_TOTAL_VALID = 175413744;

export const EU_BASELINE_SEATS: Record<Exclude<EuGroupId,'OTH'>, number> = {"LEFT":46,"GREENS":53,"SD":136,"RE":77,"EPP":188,"ECR":78,"PfE":84,"ESN":25,"NI":33};

export const EU_VOTE_PCT_2024: Record<EuGroupId, number> = {"LEFT":6.43,"GREENS":7.56,"SD":17.25,"RE":8.67,"EPP":23.16,"ECR":9.51,"PfE":10.47,"ESN":4.73,"NI":4.18,"OTH":8.03};

export const EU_VOTE_RAW_2024: Record<EuGroupId, number> = {"LEFT":11280587,"GREENS":13266138,"SD":30266452,"RE":15215347,"EPP":40623904,"ECR":16676035,"PfE":18363567,"ESN":8289025,"NI":7338963,"OTH":14093726};

// ── 27 member states ──────────────────────────────────────────────────────────
// Verified Σseats = 720 MEPs.
export const EU_COUNTRIES_DATA: EuCountry[] = [
  { id:'DE', name:"Germany", seats:96, electorate:61779636, turnout:64.74, validVotes:39796212,
    raw2024:{"LEFT":1631645,"GREENS":5770451,"SD":5531673,"RE":3143901,"EPP":12416418,"ESN":6327598,"NI":3462270,"OTH":1512256},
    seats2024:{"LEFT":4,"GREENS":15,"SD":14,"RE":8,"EPP":31,"ESN":14,"NI":10} },
  { id:'FR', name:"France", seats:81, electorate:49462981, turnout:51.49, validVotes:24753773,
    raw2024:{"LEFT":2448148,"GREENS":1361458,"SD":3423447,"RE":3614051,"EPP":1794649,"ECR":1083225,"PfE":7765259,"ESN":270806,"OTH":2992730},
    seats2024:{"LEFT":9,"GREENS":5,"SD":13,"RE":13,"EPP":6,"ECR":4,"PfE":30,"ESN":1} },
  { id:'IT', name:"Italy", seats:76, electorate:51214348, turnout:48.31, validVotes:23415587,
    raw2024:{"LEFT":2866848,"GREENS":1059946,"SD":5645498,"EPP":2364974,"ECR":6731981,"PfE":2100378,"OTH":2645962},
    seats2024:{"LEFT":10,"GREENS":4,"SD":21,"EPP":9,"ECR":24,"PfE":8} },
  { id:'ES', name:"Spain", seats:61, electorate:38050286, turnout:46.39, validVotes:17527438,
    raw2024:{"LEFT":1138115,"GREENS":1119419,"SD":5291534,"RE":285697,"EPP":5996137,"PfE":1687892,"NI":1244448,"OTH":764196},
    seats2024:{"LEFT":4,"GREENS":4,"SD":20,"RE":1,"EPP":22,"PfE":6,"NI":4} },
  { id:'PL', name:"Poland", seats:53, electorate:29098155, turnout:40.65, validVotes:11761994,
    raw2024:{"SD":741006,"RE":270918,"EPP":4900831,"ECR":4253137,"ESN":710424,"NI":710424,"OTH":175254},
    seats2024:{"SD":3,"RE":1,"EPP":23,"ECR":20,"ESN":3,"NI":3} },
  { id:'RO', name:"Romania", seats:33, electorate:18025329, turnout:52.4, validVotes:8313872,
    raw2024:{"GREENS":256067,"SD":2336854,"RE":724138,"EPP":2238269,"ECR":1241261,"NI":418188,"OTH":1099095},
    seats2024:{"GREENS":1,"SD":11,"RE":3,"EPP":10,"ECR":6,"NI":2} },
  { id:'NL', name:"Netherlands", seats:31, electorate:13542363, turnout:46.18, validVotes:6232198,
    raw2024:{"LEFT":281695,"GREENS":976897,"SD":657185,"RE":1230859,"EPP":1159812,"ECR":228098,"PfE":1057604,"OTH":640048},
    seats2024:{"LEFT":1,"GREENS":6,"SD":4,"RE":7,"EPP":6,"ECR":1,"PfE":6} },
  { id:'BE', name:"Belgium", seats:22, electorate:8537902, turnout:89.01, validVotes:7133784,
    raw2024:{"LEFT":763315,"GREENS":710525,"SD":1100029,"RE":1680006,"EPP":609939,"ECR":996590,"PfE":1034399,"OTH":238981},
    seats2024:{"LEFT":2,"GREENS":2,"SD":4,"RE":5,"EPP":3,"ECR":3,"PfE":3} },
  { id:'CZ', name:"Czechia", seats:21, electorate:8212628, turnout:36.45, validVotes:2968889,
    raw2024:{"GREENS":184071,"EPP":588879,"ECR":330586,"PfE":1080676,"ESN":170117,"NI":283826,"OTH":330734},
    seats2024:{"GREENS":1,"EPP":5,"ECR":3,"PfE":9,"ESN":1,"NI":2} },
  { id:'EL', name:"Greece", seats:21, electorate:9814685, turnout:41.24, validVotes:3976085,
    raw2024:{"LEFT":593232,"SD":508541,"EPP":1125630,"ECR":369776,"PfE":120873,"NI":676730,"OTH":581303},
    seats2024:{"LEFT":4,"SD":3,"EPP":7,"ECR":2,"PfE":1,"NI":4} },
  { id:'HU', name:"Hungary", seats:21, electorate:7655344, turnout:59.46, validVotes:4569620,
    raw2024:{"SD":366940,"EPP":1352608,"PfE":2048104,"ESN":306622,"OTH":495346},
    seats2024:{"SD":2,"EPP":7,"PfE":11,"ESN":1} },
  { id:'PT', name:"Portugal", seats:21, electorate:10789781, turnout:36.47, validVotes:3874771,
    raw2024:{"LEFT":330905,"SD":1268988,"RE":358804,"EPP":1229852,"PfE":387090,"OTH":299132},
    seats2024:{"LEFT":2,"SD":8,"RE":2,"EPP":7,"PfE":2} },
  { id:'SE', name:"Sweden", seats:21, electorate:7942272, turnout:53.39, validVotes:4198011,
    raw2024:{"LEFT":464300,"GREENS":581425,"SD":1039847,"RE":489908,"EPP":975618,"ECR":552878,"OTH":94035},
    seats2024:{"LEFT":2,"GREENS":3,"SD":5,"RE":3,"EPP":5,"ECR":3} },
  { id:'AT', name:"Austria", seats:20, electorate:6372204, turnout:56.25, validVotes:3523934,
    raw2024:{"GREENS":390452,"SD":818257,"RE":357327,"EPP":864069,"PfE":893670,"OTH":200159},
    seats2024:{"GREENS":2,"SD":5,"RE":2,"EPP":5,"PfE":6} },
  { id:'BG', name:"Bulgaria", seats:17, electorate:6170472, turnout:33.78, validVotes:2013060,
    raw2024:{"SD":141116,"RE":489039,"EPP":571038,"ECR":121589,"ESN":281426,"OTH":408852},
    seats2024:{"SD":2,"RE":5,"EPP":6,"ECR":1,"ESN":3} },
  { id:'DK', name:"Denmark", seats:15, electorate:4301255, turnout:58.25, validVotes:2447783,
    raw2024:{"LEFT":172324,"GREENS":426404,"SD":381120,"RE":679260,"EPP":386505,"ECR":180891,"PfE":155924,"OTH":65355},
    seats2024:{"LEFT":1,"GREENS":3,"SD":3,"RE":4,"EPP":2,"ECR":1,"PfE":1} },
  { id:'FI', name:"Finland", seats:15, electorate:4546589, turnout:40.38, validVotes:1829249,
    raw2024:{"LEFT":316460,"GREENS":206705,"SD":272558,"RE":327436,"EPP":453654,"ECR":139023,"OTH":113413},
    seats2024:{"LEFT":3,"GREENS":2,"SD":2,"RE":3,"EPP":4,"ECR":1} },
  { id:'SK', name:"Slovakia", seats:15, electorate:4377093, turnout:34.38, validVotes:1476968,
    raw2024:{"RE":410745,"EPP":105456,"ESN":185064,"NI":471744,"OTH":303959},
    seats2024:{"RE":6,"EPP":1,"ESN":1,"NI":7} },
  { id:'IE', name:"Ireland", seats:14, electorate:3554450, turnout:50.65, validVotes:1745230,
    raw2024:{"LEFT":194419,"SD":58989,"RE":709261,"EPP":362833,"OTH":419728},
    seats2024:{"LEFT":3,"SD":1,"RE":6,"EPP":4} },
  { id:'HR', name:"Croatia", seats:12, electorate:3731860, turnout:21.35, validVotes:752661,
    raw2024:{"GREENS":44558,"SD":195391,"EPP":260421,"ECR":66385,"OTH":185906},
    seats2024:{"GREENS":1,"SD":4,"EPP":6,"ECR":1} },
  { id:'LT', name:"Lithuania", seats:11, electorate:2387327, turnout:28.97, validVotes:678319,
    raw2024:{"GREENS":40360,"SD":121962,"RE":91573,"EPP":144685,"ECR":101137,"ESN":36968,"OTH":141634},
    seats2024:{"GREENS":1,"SD":2,"RE":2,"EPP":3,"ECR":2,"ESN":1} },
  { id:'LV', name:"Latvia", seats:9, electorate:1541102, turnout:33.82, validVotes:514585,
    raw2024:{"GREENS":38337,"SD":36690,"RE":48165,"EPP":129109,"ECR":155662,"PfE":31698,"OTH":74924},
    seats2024:{"GREENS":1,"SD":1,"RE":1,"EPP":2,"ECR":3,"PfE":1} },
  { id:'SI', name:"Slovenia", seats:9, electorate:1689586, turnout:41.8, validVotes:674111,
    raw2024:{"GREENS":70984,"SD":52311,"RE":149046,"EPP":257982,"OTH":143788},
    seats2024:{"GREENS":1,"SD":1,"RE":2,"EPP":5} },
  { id:'EE', name:"Estonia", seats:7, electorate:980014, turnout:37.64, validVotes:368126,
    raw2024:{"SD":71048,"RE":111542,"EPP":79147,"ECR":54483,"OTH":51906},
    seats2024:{"SD":2,"RE":2,"EPP":2,"ECR":1} },
  { id:'CY', name:"Cyprus", seats:6, electorate:683432, turnout:58.86, validVotes:368455,
    raw2024:{"LEFT":79181,"SD":35814,"EPP":91303,"ECR":41230,"NI":71333,"OTH":49594},
    seats2024:{"LEFT":1,"SD":1,"EPP":2,"ECR":1,"NI":1} },
  { id:'LU', name:"Luxembourg", seats:6, electorate:319410, turnout:82.29, validVotes:238771,
    raw2024:{"GREENS":28079,"SD":51861,"RE":43671,"EPP":54726,"ECR":28103,"OTH":32331},
    seats2024:{"GREENS":1,"SD":1,"RE":1,"EPP":2,"ECR":1} },
  { id:'MT', name:"Malta", seats:6, electorate:370184, turnout:72.98, validVotes:260258,
    raw2024:{"SD":117793,"EPP":109360,"OTH":33105},
    seats2024:{"SD":3,"EPP":3} },
];
