// AUTO-GENERATED by gr_src/gen-data.cjs — June 2023 Greek legislative election (verified vs official).
// Reinforced PR: 300 seats, 3% national threshold, winner's bonus up to 50; reproduces the official result.

export type GrPartyId = 'KKE' | 'SYRIZA' | 'PE' | 'PASOK' | 'ND' | 'EL' | 'NIKI' | 'SPAR';

export type GrParty = {
  id: GrPartyId; name: string; full: string; color: string; ideo: number;
  leader: string; wiki: string; votes2023: number; pct2023: number; seats2023: number;
};

export const GR_PARTIES: GrParty[] = [
  { id:'KKE', name:"KKE", full:"Communist Party of Greece", color:'#D80000', ideo:0, leader:"Dimitris Koutsoumbas", wiki:'Dimitris_Koutsoumpas', votes2023:401224, pct2023:7.69, seats2023:21 },
  { id:'SYRIZA', name:"SYRIZA", full:"SYRIZA – Progressive Alliance", color:'#E14B8A', ideo:1, leader:"Alexis Tsipras", wiki:'Alexis_Tsipras', votes2023:930013, pct2023:17.83, seats2023:47 },
  { id:'PE', name:"Course of Freedom", full:"Course of Freedom (Plefsi Eleftherias)", color:'#9F1897', ideo:2, leader:"Zoe Konstantopoulou", wiki:'Zoe_Konstantopoulou', votes2023:165523, pct2023:3.17, seats2023:8 },
  { id:'PASOK', name:"PASOK", full:"PASOK – Movement for Change", color:'#00A93B', ideo:3, leader:"Nikos Androulakis", wiki:'Nikos_Androulakis', votes2023:617487, pct2023:11.84, seats2023:32 },
  { id:'ND', name:"New Democracy", full:"New Democracy (Néa Dimokratía)", color:'#1C7FE0', ideo:4, leader:"Kyriakos Mitsotakis", wiki:'Kyriakos_Mitsotakis', votes2023:2115322, pct2023:40.56, seats2023:158 },
  { id:'EL', name:"Greek Solution", full:"Greek Solution (Ellinikí Lýsi)", color:'#0A3D7A', ideo:5, leader:"Kyriakos Velopoulos", wiki:'Kyriakos_Velopoulos', votes2023:231491, pct2023:4.44, seats2023:12 },
  { id:'NIKI', name:"Niki", full:"Niki – Victory", color:'#7B6CCB', ideo:6, leader:"Dimitris Natsios", wiki:'Dimitris_Natsios', votes2023:193124, pct2023:3.7, seats2023:10 },
  { id:'SPAR', name:"Spartans", full:"Spartans (Spartiátes)", color:'#C9A227', ideo:7, leader:"Vasilis Stigkas", wiki:'Vasilis_Stigkas', votes2023:243922, pct2023:4.68, seats2023:12 },
];

export const GR_OTHERS_PCT_2023 = 6.08;
export const GR_META = { election:'June 2023', valid:5215207, registered:9895541, totalSeats:300, stateSeats:15, constituencySeats:285, threshold:3, bonusMax:50 } as const;

// Per-constituency: id = electoral order 1-59 (matches geojson feature id); seats = magnitude;
// valid = valid votes (raw-vote scale); v2023 = each party's % of valid (others = remainder).
export type GrConst = { id: number; name: string; seats: number; valid: number; v2023: Partial<Record<GrPartyId, number>> };
export const GR_CONSTITUENCIES: GrConst[] = [
  { id:1, name:"Athens A", seats:13, valid:219107, v2023:{ KKE:8.904, SYRIZA:19.966, PE:3.389, PASOK:6.864, ND:43.272, EL:2.951, NIKI:2.629, SPAR:4.223 } },
  { id:2, name:"Athens B1 (North)", seats:16, valid:322031, v2023:{ KKE:8.98, SYRIZA:16.951, PE:3.419, PASOK:7.642, ND:47.321, EL:2.636, NIKI:2.735, SPAR:3.079 } },
  { id:3, name:"Athens B2 (West)", seats:12, valid:206180, v2023:{ KKE:12.142, SYRIZA:21.125, PE:4.053, PASOK:8.922, ND:34.661, EL:4.023, NIKI:2.812, SPAR:5.024 } },
  { id:4, name:"Athens B3 (South)", seats:19, valid:350883, v2023:{ KKE:10.167, SYRIZA:18.66, PE:3.676, PASOK:7.907, ND:42.324, EL:3.348, NIKI:2.731, SPAR:3.759 } },
  { id:5, name:"Piraeus A", seats:5, valid:93353, v2023:{ KKE:8.021, SYRIZA:16.578, PE:3.921, PASOK:6.705, ND:47.269, EL:3.536, NIKI:3.076, SPAR:4.574 } },
  { id:6, name:"Piraeus B", seats:8, valid:136701, v2023:{ KKE:11.49, SYRIZA:19.359, PE:4.412, PASOK:7.605, ND:37.237, EL:4.53, NIKI:3.005, SPAR:5.6 } },
  { id:7, name:"East Attica", seats:12, valid:223582, v2023:{ KKE:7.192, SYRIZA:15.523, PE:3.627, PASOK:8, ND:46.658, EL:4.596, NIKI:3.175, SPAR:4.881 } },
  { id:8, name:"West Attica", seats:4, valid:71098, v2023:{ KKE:10.113, SYRIZA:15.832, PE:3.153, PASOK:8.041, ND:39.74, EL:5.951, NIKI:3.439, SPAR:7.609 } },
  { id:9, name:"Aitoloakarnania", seats:7, valid:117550, v2023:{ KKE:7.093, SYRIZA:21.635, PE:2.226, PASOK:14.198, ND:38.851, EL:2.81, NIKI:3.959, SPAR:5.008 } },
  { id:10, name:"Argolida", seats:3, valid:51360, v2023:{ KKE:5.265, SYRIZA:15.249, PE:2.523, PASOK:15.014, ND:43.281, EL:3.871, NIKI:3.429, SPAR:5.387 } },
  { id:11, name:"Arcadia", seats:3, valid:52380, v2023:{ KKE:6.497, SYRIZA:16.858, PE:2.845, PASOK:16.281, ND:41.508, EL:3.669, NIKI:2.86, SPAR:4.469 } },
  { id:12, name:"Arta", seats:2, valid:42248, v2023:{ KKE:7.655, SYRIZA:28.943, PE:1.792, PASOK:10.836, ND:37.498, EL:2.616, NIKI:2.358, SPAR:3.581 } },
  { id:13, name:"Achaea", seats:9, valid:152290, v2023:{ KKE:7.567, SYRIZA:23.202, PE:3.51, PASOK:13.7, ND:34.036, EL:3.897, NIKI:4.326, SPAR:4.195 } },
  { id:14, name:"Boeotia", seats:3, valid:57873, v2023:{ KKE:8.89, SYRIZA:18.314, PE:3.121, PASOK:14.07, ND:37.121, EL:4.354, NIKI:3.418, SPAR:5.365 } },
  { id:15, name:"Grevena", seats:1, valid:19419, v2023:{ KKE:8.116, SYRIZA:17.977, PE:2.096, PASOK:16.474, ND:39.812, EL:3.8, NIKI:3.373, SPAR:4.192 } },
  { id:16, name:"Drama", seats:3, valid:52792, v2023:{ KKE:4.074, SYRIZA:13.273, PE:2.983, PASOK:15.254, ND:39.389, EL:6.831, NIKI:6.331, SPAR:6.007 } },
  { id:17, name:"Dodecanese", seats:5, valid:90499, v2023:{ KKE:4.341, SYRIZA:13.07, PE:2.953, PASOK:14.518, ND:46.97, EL:4.456, NIKI:3.025, SPAR:5.81 } },
  { id:18, name:"Evros", seats:4, valid:76539, v2023:{ KKE:3.78, SYRIZA:15, PE:1.763, PASOK:12.561, ND:44.179, EL:8.826, NIKI:3.474, SPAR:5.46 } },
  { id:19, name:"Euboea", seats:6, valid:108917, v2023:{ KKE:7.64, SYRIZA:17.773, PE:3.886, PASOK:12.987, ND:38.626, EL:4.887, NIKI:3.211, SPAR:5.301 } },
  { id:20, name:"Evrytania", seats:1, valid:12055, v2023:{ KKE:5.375, SYRIZA:19.511, PE:2.489, PASOK:15.977, ND:41.219, EL:3.053, NIKI:4.43, SPAR:3.791 } },
  { id:21, name:"Zakynthos", seats:1, valid:19955, v2023:{ KKE:12.819, SYRIZA:16.402, PE:2.922, PASOK:13.465, ND:39.213, EL:2.876, NIKI:1.869, SPAR:5.172 } },
  { id:22, name:"Ilia", seats:5, valid:79694, v2023:{ KKE:5.476, SYRIZA:20.127, PE:2.885, PASOK:19.738, ND:37.446, EL:3.767, NIKI:2.196, SPAR:4.586 } },
  { id:23, name:"Imathia", seats:4, valid:74598, v2023:{ KKE:5.981, SYRIZA:14.73, PE:3.144, PASOK:11.754, ND:39.185, EL:8.215, NIKI:5.481, SPAR:5.812 } },
  { id:24, name:"Heraklion", seats:8, valid:155132, v2023:{ KKE:5.497, SYRIZA:20.517, PE:2.441, PASOK:22.982, ND:35.161, EL:2.225, NIKI:2.028, SPAR:3.77 } },
  { id:25, name:"Thesprotia", seats:1, valid:27031, v2023:{ KKE:5.83, SYRIZA:19.134, PE:2.209, PASOK:15.068, ND:43.332, EL:2.889, NIKI:2.338, SPAR:3.859 } },
  { id:26, name:"Thessaloniki A", seats:17, valid:290384, v2023:{ KKE:8.173, SYRIZA:17.521, PE:4.44, PASOK:8.14, ND:35.281, EL:7.97, NIKI:5.361, SPAR:5.025 } },
  { id:27, name:"Thessaloniki B", seats:9, valid:178444, v2023:{ KKE:6.621, SYRIZA:13.577, PE:3.784, PASOK:9.847, ND:40.112, EL:7.952, NIKI:6.489, SPAR:5.288 } },
  { id:28, name:"Ioannina", seats:5, valid:88911, v2023:{ KKE:8.008, SYRIZA:22.417, PE:2.181, PASOK:13.526, ND:38.713, EL:3.061, NIKI:3.162, SPAR:3.495 } },
  { id:29, name:"Kavala", seats:4, valid:69996, v2023:{ KKE:5.576, SYRIZA:14.152, PE:2.859, PASOK:12.382, ND:42.694, EL:5.397, NIKI:5.533, SPAR:5.43 } },
  { id:30, name:"Karditsa", seats:4, valid:67478, v2023:{ KKE:7.514, SYRIZA:16.666, PE:1.706, PASOK:16.58, ND:43.091, EL:2.82, NIKI:2.742, SPAR:4.882 } },
  { id:31, name:"Kastoria", seats:1, valid:27187, v2023:{ KKE:4.094, SYRIZA:16.611, PE:2.395, PASOK:11.524, ND:44.786, EL:5.315, NIKI:4.988, SPAR:4.778 } },
  { id:32, name:"Corfu", seats:3, valid:49779, v2023:{ KKE:8.745, SYRIZA:18.556, PE:6.388, PASOK:12.061, ND:36.742, EL:3.341, NIKI:2.383, SPAR:5.364 } },
  { id:33, name:"Kefallonia", seats:1, valid:20885, v2023:{ KKE:12.363, SYRIZA:19.694, PE:3.859, PASOK:10.438, ND:38.152, EL:3.093, NIKI:1.963, SPAR:4.898 } },
  { id:34, name:"Kilkis", seats:3, valid:48989, v2023:{ KKE:6.685, SYRIZA:12.627, PE:2.568, PASOK:14.324, ND:39.627, EL:7.13, NIKI:6.975, SPAR:5.503 } },
  { id:35, name:"Kozani", seats:4, valid:83908, v2023:{ KKE:7.263, SYRIZA:17.481, PE:2.609, PASOK:14.749, ND:36.688, EL:4.688, NIKI:6.271, SPAR:4.296 } },
  { id:36, name:"Corinthia", seats:4, valid:75793, v2023:{ KKE:4.37, SYRIZA:17.273, PE:3.163, PASOK:13.665, ND:41.826, EL:4.259, NIKI:4.394, SPAR:5.644 } },
  { id:37, name:"Cyclades", seats:4, valid:66561, v2023:{ KKE:5.744, SYRIZA:14.142, PE:3.747, PASOK:12.435, ND:46.676, EL:3.927, NIKI:2.957, SPAR:3.993 } },
  { id:38, name:"Laconia", seats:3, valid:47239, v2023:{ KKE:5.061, SYRIZA:12.797, PE:2.384, PASOK:14.774, ND:47.833, EL:3.51, NIKI:2.246, SPAR:7.481 } },
  { id:39, name:"Larissa", seats:8, valid:143764, v2023:{ KKE:9.29, SYRIZA:17.534, PE:2.572, PASOK:12.254, ND:39.352, EL:3.879, NIKI:4.102, SPAR:5.131 } },
  { id:40, name:"Lasithi", seats:2, valid:39453, v2023:{ KKE:4.758, SYRIZA:14.625, PE:2.517, PASOK:25.582, ND:39.749, EL:2.573, NIKI:2.083, SPAR:2.938 } },
  { id:41, name:"Lesvos", seats:3, valid:52864, v2023:{ KKE:14.643, SYRIZA:13.487, PE:2.06, PASOK:14.689, ND:39.808, EL:3.465, NIKI:2.839, SPAR:4.112 } },
  { id:42, name:"Lefkada", seats:1, valid:13611, v2023:{ KKE:11.799, SYRIZA:17.515, PE:2.711, PASOK:12.387, ND:41.709, EL:1.984, NIKI:1.91, SPAR:3.46 } },
  { id:43, name:"Magnisia", seats:5, valid:95864, v2023:{ KKE:7.898, SYRIZA:17.25, PE:3.671, PASOK:9.372, ND:42.389, EL:4.093, NIKI:4.044, SPAR:4.898 } },
  { id:44, name:"Messinia", seats:5, valid:89338, v2023:{ KKE:7.438, SYRIZA:17.5, PE:2.568, PASOK:11.137, ND:43.714, EL:3.812, NIKI:2.587, SPAR:5.962 } },
  { id:45, name:"Xanthi", seats:3, valid:55235, v2023:{ KKE:3.224, SYRIZA:28.487, PE:2.189, PASOK:18.356, ND:30.321, EL:3.978, NIKI:3.163, SPAR:4.401 } },
  { id:46, name:"Pella", seats:4, valid:79149, v2023:{ KKE:3.75, SYRIZA:18.405, PE:2.647, PASOK:12.487, ND:38.415, EL:7.65, NIKI:7.147, SPAR:5.13 } },
  { id:47, name:"Pieria", seats:4, valid:70186, v2023:{ KKE:5.135, SYRIZA:13.631, PE:2.633, PASOK:13.107, ND:38.795, EL:7.003, NIKI:9.257, SPAR:5.56 } },
  { id:48, name:"Preveza", seats:2, valid:34063, v2023:{ KKE:7.918, SYRIZA:20.949, PE:1.891, PASOK:15.013, ND:41.579, EL:2.642, NIKI:1.835, SPAR:3.781 } },
  { id:49, name:"Rethymno", seats:2, valid:43723, v2023:{ KKE:4.083, SYRIZA:18.713, PE:2.635, PASOK:25.712, ND:36.667, EL:2.2, NIKI:2.781, SPAR:2.987 } },
  { id:50, name:"Rodopi", seats:3, valid:54623, v2023:{ KKE:3.158, SYRIZA:33.601, PE:1.338, PASOK:19.003, ND:28.885, EL:4.134, NIKI:2.645, SPAR:3.131 } },
  { id:51, name:"Samos", seats:1, valid:22708, v2023:{ KKE:17.963, SYRIZA:14.88, PE:3.347, PASOK:9.935, ND:36.053, EL:5.179, NIKI:2.171, SPAR:3.849 } },
  { id:52, name:"Serres", seats:5, valid:99418, v2023:{ KKE:5.024, SYRIZA:12.881, PE:2.597, PASOK:11.446, ND:45.639, EL:7.243, NIKI:4.686, SPAR:5.17 } },
  { id:53, name:"Trikala", seats:4, valid:75994, v2023:{ KKE:8.598, SYRIZA:17.176, PE:1.848, PASOK:14.862, ND:41.397, EL:2.94, NIKI:4.436, SPAR:3.967 } },
  { id:54, name:"Fthiotida", seats:4, valid:83684, v2023:{ KKE:7.238, SYRIZA:17.572, PE:2.22, PASOK:12.682, ND:43.299, EL:3.912, NIKI:3.05, SPAR:5.211 } },
  { id:55, name:"Florina", seats:2, valid:28899, v2023:{ KKE:5.647, SYRIZA:21.81, PE:2.343, PASOK:15.118, ND:34.42, EL:5.128, NIKI:5.37, SPAR:4.308 } },
  { id:56, name:"Fokida", seats:1, valid:21713, v2023:{ KKE:8.087, SYRIZA:16.101, PE:3.113, PASOK:11.601, ND:44.651, EL:3.652, NIKI:2.773, SPAR:4.578 } },
  { id:57, name:"Chalkidiki", seats:3, valid:57583, v2023:{ KKE:4.668, SYRIZA:13.695, PE:3.133, PASOK:14.518, ND:39.536, EL:6.304, NIKI:6.564, SPAR:5.545 } },
  { id:58, name:"Chania", seats:4, valid:78758, v2023:{ KKE:8.419, SYRIZA:18.436, PE:3.705, PASOK:11.206, ND:40.523, EL:3.097, NIKI:2.729, SPAR:4.638 } },
  { id:59, name:"Chios", seats:2, valid:28498, v2023:{ KKE:6.674, SYRIZA:10.52, PE:2.397, PASOK:19.889, ND:46.494, EL:2.965, NIKI:2.481, SPAR:3.59 } },
];
